import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The RootLayout component.
 *
 * This component serves as the root layout for the application.
 * It wraps the application with the ClerkProvider, enabling authentication features.
 * The children are rendered within the HTML body tag.
 *
 * @param {React.ReactNode} children - The content to be rendered inside the layout.
 *
 * @returns A JSX element containing the wrapped application layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="light">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
